apiVersion: v1
kind: Service
metadata:
    name: "iamaks99-d5d7"
    labels:
        app: "iamaks99-d5d7"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "iamaks99-d5d7"