version: "2.4"
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingFederate getting started demo
#-
#-                +---------------+
#-                | PingFederate  |
#-                +---------------+
#-
#- To access PingFederate Console
#-
#-    https://localhost:9999/pingfederate/app
#-
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

services:
  pingfederate:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingfederate:10.2.2-alpine-az11-GDO-542-delegator-unpriviliged-user-d2a6
    #environment:
    #  - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
    #  - SERVER_PROFILE_PATH=baseline/pingfederate
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet
    volumes:
      - /Users/henryrecker/workspace/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in

networks:
  pingnet:

volumes:
  pingfederate-out:
