on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n iamgithub -g iamgithub9565-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n iamgithub --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n iamgithub --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n iamgithub --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: iamgithub.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/99-helper-scripts/ping-bulkconfigtool" -f  "99-helper-scripts/ping-bulkconfigtool/Dockerfile" -t iamgithub.azurecr.io/iamaks99:${{ github.sha }} --label dockerfile-path=99-helper-scripts/ping-bulkconfigtool/Dockerfile
        docker push iamgithub.azurecr.io/iamaks99:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_iamaks99_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep iam-github | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace iam-github`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: iam-github
        container-registry-url: iamgithub.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: iamaks99dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: iam-github
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          iamgithub.azurecr.io/iamaks99:${{ github.sha }}
        imagepullsecrets: |
          iamaks99dockerauth   
